CREATE TABLE IF NOT EXISTS cidades (
    ID INT UNSIDNED NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(255) NOT NULL,
    estado_id int unsigned NOT NULL,
    area DECIMAL(10, 2),
    PRIMARY KEY (id),
    FOREIGN KEY (estado_id) REFERENCES estados (ID)
);

CREATE TABLE IF NOT EXISTS TESTE (
    ID INT UNSIDNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
);